[project]
name = "triton-puzzles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.4.0",
    "jaxtyping>=0.3.2",
    "pip>=25.1.1",
    "pycairo>=1.28.0",
]
